server:
  port: ${PORT}

spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}

  jpa:
    hibernate:
      enable: true
      ddl_auto: update
    show_sql: true

jwt:
  secret: ${SECRET}
  access_time: ${ACCESS_TIME}
  refresh_time: ${REFRESH_TIME}
